<a href="https://colab.research.google.com/github/ManishBhat/Project-Euler-solutions-in-Python/blob/master/Hello_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [11]:
%tensorflow_version 2.x
import numpy
import tensorflow as tf
print(tf.version)


<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [0]:
string = tf.Variable("this is a string",tf.string)
number = tf.Variable(324,tf.int16)
floating = tf.Variable(3.567,tf.float64)

In [0]:
rank1_tensor = tf.Variable(["Test","ok","Tim"],tf.string)
rank2_tensor = tf.Variable([["test","no","ter"],["test","yes","Hello"]],tf.string)

In [14]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [0]:
tf.rank(rank2_tensor)
rank2_tensor.shape
print(dir(rank2_tensor))

In [16]:
tensor1 = tf.ones([2,3])
tensor1.shape
print(tensor1)
tensor2 = tf.reshape(tensor1, [3,2])
print(tensor2)
tensor3 = tf.reshape(tensor1, [1,2,-1])
print(tensor3)

TensorShape([2, 3])

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


# Types of variables
1.   string
2.   int16
3.   float64

#Rank of a tensor
tf.rank(Tensor)





